trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  GOBIN:  '$(GOPATH)/bin'
  GOROOT: '/usr/local/go1.11'
  GOPATH: '$(system.defaultWorkingDirectory)/gopath'

resources:
  repositories:
    - repository: templates
      type: git
      name: Dynizer/build-templates

steps:
- template: golang-env.yaml@templates
  parameters:
    golang_goBin: '$(GOBIN)'
    golang_goRoot: '$(GOROOT)'
    golang_goPath: '$(GOPATH)'

- template: protoc.yaml@templates

- template: git-user.yaml@templates

- script: |
    go get -u gopkg.in/yaml.v2
    mkdir -p /tmp/go.dynactionize.com
    REPO_URL="https://dynactionize@dev.azure.com/dynactionize/Dynizer/_git/go-dynagatewaytypes"
    git -c http.$REPO_URL.extraHeader="Authorization: Basic $(PAT_ENC)" clone $REPO_URL /tmp/go.dynactionize.com/dynagatewaytypes
    make GO_PREFIX=/tmp go
    cd /tmp/go.dynactionize.com/dynagatewaytypes
    git add --all
    git commit -m "$(Build.BuildNumber)"
    git -c http.$REPO_URL.extraHeader="Authorization: Basic $(PAT_ENC)" push
  displayName: 'protobuf to go and push'